HW01. CLI
Galoev/Software-Design pull request #1
Opened 2020-09-06 17:17 UTC by Galoev

2020-09-07 19:23 UTC, yurii-litvinov requested changes
Теряется stderr от внешних процессов --- попробуйте git ololo, например. Хочется, чтобы он тоже выводился.

В остальном очень годно, но надо всё-таки поправить немного

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/CLI.java
> +import java.util.List;
Надо разложить классы по пакетам, в Java не принято всё в пакет по умолчанию добавлять. Причём, пакеты должны использовать [каноничную схему именования](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/CLI.java
> +public class CLI {
К этому классу тоже по-хорошему нужен комментарий

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/CLI.java
> +    private static final Scanner scanner = new Scanner(System.in);
Когда вся система --- это набор статических полей, это пугает. А что если нам надо будет две консоли в рамках одного процесса иметь? Ну, например, две вкладки с консолью в терминале.

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/CommandCat.java
> +            StringBuilder result = new StringBuilder();
Когда тип очевиден из правой части  присваивания, лучше var

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/Environment.java
> +    public String getVal(String var){
О, пробела не хватает

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/Lexer.java
> +    public List<Token> parse(String commandLine) throws Exception{
Кстати, и тут

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/Parser.java
> +            i+=1;
И тут

2020-09-07 19:23 UTC, yurii-litvinov commented on src/test/java/CommandTest.java
> +            e.printStackTrace();
Зачем? Если будет брошено исключение, тест всё равно так будет помечен как пройденный, и этот стектрейс никто не увидит просто потому, что не будет повода в логи посмотреть. Дайте ему упасть. Вообще, try-catch в тестах всегда выглядит подозрительно --- будто автор не знает, ждать тут исключение от системы или нет.

2020-09-07 19:23 UTC, yurii-litvinov commented on src/test/java/LexerTest.java
> +    public void test1() throws Exception {
Имена тестов не очень :)

2020-09-07 19:23 UTC, yurii-litvinov commented on src/main/java/CommandCat.java
> +                    throw new Exception("File " + arg + "not found");
Неплохо бы пробел в выводе перед "not"

2020-09-07 19:23 UTC, yurii-litvinov commented on src/test/java/CommandTest.java
> +                Arrays.asList("echo", text),
Такой тест заведомо не пройдёт под Windows, хотя сама CLI и все остальные тесты под ней прекрасно работают. Неоправданная некроссплатформенность

2020-09-08 21:18 UTC, Galoev commented on src/main/java/CLI.java
> +import java.util.List;
Да, не сразу заметил эту проблему, а потом когда заметил, попытался добавить пакеты, но что-то не получилось и я оставил пакет по умолчанию. Но сейчас уже всё исправил

2020-09-08 21:19 UTC, Galoev commented on src/main/java/CLI.java
> +public class CLI {
Добавил

2020-09-08 21:19 UTC, Galoev commented on src/main/java/CLI.java
> +    private static final Scanner scanner = new Scanner(System.in);
Исправил

2020-09-08 21:21 UTC, Galoev commented on src/main/java/CommandCat.java
> +            StringBuilder result = new StringBuilder();
Нам не рассказывали про var на курсе по Java, но я знал про его существования, но не знал как он применяется. Я предполагал, что она работает как auto в C++. Вроде, везде поменял на var, где можно

2020-09-08 21:21 UTC, Galoev commented on src/main/java/Environment.java
> +    public String getVal(String var){
Исправил

2020-09-08 21:21 UTC, Galoev commented on src/main/java/Lexer.java
> +    public List<Token> parse(String commandLine) throws Exception{
Исправил

2020-09-08 21:22 UTC, Galoev commented on src/main/java/Parser.java
> +            i+=1;
Исправил

2020-09-09 00:40 UTC, Galoev commented on src/test/java/CommandTest.java
> +            e.printStackTrace();
Удалил везде  try-catch и добавил в сигнатуру методов, что они бросают ошибки. Я просто думал, что лучше делать try-catch, чем в сигнатуре метода указывать, что метод может выбросить исключение

2020-09-09 00:40 UTC, Galoev commented on src/test/java/LexerTest.java
> +    public void test1() throws Exception {
Поменял имена, некоторых тестов

2020-09-09 00:40 UTC, Galoev commented on src/main/java/CommandCat.java
> +                    throw new Exception("File " + arg + "not found");
Исправил

2020-09-09 00:40 UTC, Galoev commented on src/test/java/CommandTest.java
> +                Arrays.asList("echo", text),
Исправил

2020-09-09 17:18 UTC, yurii-litvinov commented on src/main/java/CommandCat.java
> +            StringBuilder result = new StringBuilder();
Ага, как auto. Вообще, это дело вкуса, var очень долго не добавляли в стандарт потому, что он типа ухудшает читаемость кода и понижает надёжность программы, ослабляя ограничения на типы, проверяемые компилятором. И многие Java-программисты до сих пор придерживаются такой позиции. Но, например, в мире .NET все давно пользуются var-ами и очень довольны.

2020-09-09 17:19 UTC, yurii-litvinov commented on src/test/java/CommandTest.java
> +            e.printStackTrace();
Да, для тестов это вполне нормально, лучше добавить `throws Exception` и дать упасть

2020-09-09 17:28 UTC, yurii-litvinov approved these changes
Все основные замечания поправлены, зачтена

2020-09-09 17:28 UTC, yurii-litvinov commented on build.gradle
> +mainClassName = 'CLI'
Полностью квалифицированное имя у него теперь другое, так что gradle run не запускается :)

2020-09-09 17:28 UTC, yurii-litvinov commented on src/test/java/com/galoev/CommandTest.java
> +                Arrays.asList("echo", text),
Всё ещё не работает, под чистой Windows (без MSYS, Cygwin и подобных штук) echo нету. Точнее, echo есть, но это не программа, а встроенная команда интерпретатора cmd, так что запустить её как внешний процесс без запуска шелла не выйдет.

2022-05-27 20:30 UTC, closed without merging